name: Build and Push
on:
    push:
        branches:
            - 'release/v[0-9]+.[0-9]+'
jobs:
    scan:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with: 
                ref: ${{ github.ref }} 

            - name: Run trivy scanner
              uses: aquasecurity/trivy-action@master
              with:
                format: 'table'
                scan-type: 'fs'
                severity: 'CRITICAL'
                exit-code: '0'
                ignore-unfixed: true
                output: 'trivy-results.txt'
            
           
            
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                push: true
                tags: howdybunny/go-fortune:${{ github.sha }}

            
            
            - name: Install Cosign
              uses: sigstore/cosign-installer@v3.5.0
            
            
            - name: Sign image with a key
              run: |
                images=""
                for tag in ${TAGS}; do
                  images+="${tag}"
                done
                cosign generate-key-pair
                cosign sign --yes --key cosign.key ${images}
                
              env:
                TAGS: 'howdybunny/go-fortune:${{ github.sha }}'
                
                
                
            - name: Slack Notification
              uses: rtCamp/action-slack-notify@v2
              env:
                SLACK_CHANNEL: workshopsubtest
                SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
                SLACK_ICON: https://github.com/rtCamp.png?size=48
                
                SLACK_TITLE: Image build and signed
                ENABLE_ESCAPES: true
                SLACK_MESSAGE: '*Name:* Zheng Jie Cheng\n*Metriculation:* e1327869\n*Email:* e1327869@u.nus.edu\n*Git:* https://github.com/HowdyBunny/CICDWorkshop\n*Image:* https://hub.docker.com/repository/docker/howdybunny/go-fortune/general'
                SLACK_WEBHOOK: ${{ secrets.CICDTEST_BYMYSELF }}
                
            
            
        