name: My first workflow
on:
    push:
        branches:
            - 'release/v[0-9]+.[0-9]+'
jobs:
    scan:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
              with: 
                ref: ${{ github.ref }} 
            - name: Run trivy scanner
              uses: aquasecurity/trivy-action@master
              with:
                scan-type: 'fs'
                severity: 'CRITICAL'
                exit-code: '0'
                format: 'table'
                output: 'trivy-results.txt'
            
            - name: Send Slack Notification
              id: slack 
              uses: slackapi/slack-github-action@v1.26.0
              with: 
                slack-channel: "#channel-name" 
                payload: |
                    {
                        "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
                        "blocks": [
                        {
                            "type": "section",
                            "text": {
                            "type": "mrkdwn",
                            "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                            }
                        }
                        ]
                    }
              env:
                SLACK_WEBHOOK_URL: ${{ secrets.CICDTEST_BYMYSELF }} #need to change!!
            