name: My first workflow
on:
    push:
        branches:
            - 'release/v[0-9]+.[0-9]+'
jobs:
    scan:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
              with: 
                ref: ${{ github.ref }} 
            - name: Run trivy scanner
              uses: aquasecurity/trivy-action@master
              with:
                scan-type: 'fs'
                severity: 'HIGH'
                exit-code: '0'
                format: 'table'
                output: 'trivy-results.txt'
            
            - name: Send Slack Notification
              id: slack 
              uses: slackapi/slack-github-action@v1.26.0
              with: 
                slack-bot-user-oauth-access-token: ${{ secrets.CICDTEST_BYMYSELF_TOKEN }}
                channel-id: "C071M1LB3DM"
                blocks: |
                    [
                        {
                            "type": "section",
                            "text": {
                                "type": "mrkdwn",
                                "text": "Ref: ${{ github.ref }}\nEvent: ${{ github.event_name }}\nCommit: ${{ github.sha }}\nActions URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}\n\nFailed trivy scan, see uploaded report."
                            }
                        }
                    ]
              env:
                SLACK_BOT_TOKEN: ${{ secrets.CICDTEST_BYMYSELF_TOKEN}}
                