name: My first workflow
on:
    push:
        branches:
            - 'release/v[0-9]+.[0-9]+'
jobs:
    scan:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
              with: 
                ref: ${{ github.ref }} 
            - name: Run trivy scanner
              uses: aquasecurity/trivy-action@master
              with:
                scan-type: 'fs'
                severity: 'HIGH'
                exit-code: '0'
                format: 'table'
                output: 'trivy-results.txt'
            
            - name: Send Slack Notification
              id: slack 
              uses: slackapi/slack-github-action@v1.26.0
              with: 
                channel-id: "C071M1LB3DM" 
                
                run: |
                    COMMIT="${{ github.sha }}"
                    EVENT="${{ github.event_name }}"
                    REF="${{ github.ref }}"
                    ACTIONS_URL="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                    curl -X POST -H 'Content-type: application/json' \
                         --data '{"text":"Ref: $REF\nEvent: $EVENT\nCommit: $COMMIT\nActions URL: $ACTIONS_URL\nScan failed - Cheng:\nFailed trivy scan,see uploaded report"}' \
                         https://hooks.slack.com/services/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
              env:
                SLACK_BOT_TOKEN: ${{ secrets.CICDTEST_BYMYSELF_TOKEN}}
                