name: My first workflow
on:
    push:
        branches:
            - 'release/v[0-9]+.[0-9]+'
jobs:
    scan:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
              with: 
                ref: ${{ github.ref }} 
            - name: Run trivy scanner
              uses: aquasecurity/trivy-action@master
              with:
                scan-type: 'fs'
                severity: 'HIGH'
                exit-code: '0'
                format: 'table'
                output: 'trivy-results.txt'
            
            - name: Send Slack Notification
              id: slack 
              uses: slackapi/slack-github-action@v1.26.0
              with: 
                channel-name: "#workshopsubtest" 
                payload: |
                    {
                        "blocks": [
                        {
                            "text": {
                                "type": "mrkdwn",
                                "text": "Ref: $REF\nEvent: $EVENT\nCommit: $COMMIT\nActions URL: $ACTIONS_URL\nScan failed - Cheng:\nFailed trivy scan,see uploaded report"
                            }
                        }
                        ]
                    }
              env:
                SLACK_WEBHOOK_URL: ${{ secrets.CICDTEST_BYMYSELF }} #need to change!!
                SLACK_BOT_TOKEN: ${{ secrets.CICDTEST_BYMYSELF_TOKEN}}