name: My first workflow
on:
    push:
        branches:
            - 'release/v[0-9]+.[0-9]+'
jobs:
    scan:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
              with: 
                ref: ${{ github.ref }} 
            - name: Run trivy scanner
              uses: aquasecurity/trivy-action@master
              with:
                scan-type: 'fs'
                severity: 'HIGH'
                exit-code: '0'
                format: 'table'
                output: 'trivy-results.txt'
            
            - name: Slack Notification
              uses: rtCamp/action-slack-notify@v2
              env:
                  SLACK_CHANNEL: workshopsubtest
                  SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
                  SLACK_ICON: https://github.com/rtCamp.png?size=48
                  SLACKIFY_MARKDOWN: true
                  SLACK_TITLE: this
                  SLACK_MESSAGE: 'Post Content :rocket:'
                  SLACK_CUSTOM_PAYLOAD: |
                    '{
                        "blocks": [
                            {
                                "type": "section",
                                "fields": [
                                    {
                                        "type": "mrkdwn",
                                        "text": "*Ref*\n${{ github.ref }}"
                                    },
                                    {
                                        "type": "mrkdwn",
                                        "text": "*Event*\n${{ github.event_name }}"
                                    }
                                ]
                            },
                            {
                                "type": "section",
                                "fields": [
                                    {
                                        "type": "mrkdwn",
                                        "text": "*Actions URL*\n<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Build and Push>"
                                    },
                                    {
                                        "type": "mrkdwn",
                                        "text": "*Commit*\n$<{{ github.sha }}|${{ github.sha }}>"
                                    }
                                ]
                            },
                            {
                                "type": "section",
                                "fields": [
                                    {
                                        "type": "mrkdwn",
                                        "text": "*Scan failed - Cheng*\nFailed trivy scan, see uploaded report"
                                    }
                                ]
                            }
                        ]
                    }'
                  
                  SLACK_USERNAME: CICD
                  SLACK_TOKEN: ${{ secrets.CICDTEST_BYMYSELF_TOKEN }}
                  SLACK_FILE_UPLOAD: trivy-results.txt
                        


            
    