name: Build and Push
on:
    push:
        branches:
            - 'release/v[0-9]+.[0-9]+'
jobs:
    scan:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with: 
                ref: ${{ github.ref }} 

            - name: Run trivy scanner
              uses: aquasecurity/trivy-action@master
              with:
                format: 'table'
                scan-type: 'fs'
                severity: 'CRITICAL'
                exit-code: '0'
                ignore-unfixed: true
                output: 'trivy-results.txt'
            
           
            
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                push: true
                tags: howdybunny/go-fortune:${{ github.sha }}

            
            
            - name: Install Cosign
              uses: sigstore/cosign-installer@v3.5.0
            
            
            - name: Sign image with a key
              run: |
                images=""
                for tag in ${TAGS}; do
                  images+="${tag}"
                done
                cosign generate-key-pair
                cosign sign --yes --key cosign.key ${images}
              env:
                TAGS: 'howdybunny/go-fortune:${{ github.sha }}'
                
                
                
            - name: Slack Notification
              uses: rtCamp/action-slack-notify@v2
              env:
                SLACK_CHANNEL: workshopsubtest
                SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
                SLACK_ICON: https://github.com/rtCamp.png?size=48
                
                SLACK_TITLE: Image build and signed
                SLACKIFY_MARKDOWN: true
                SLACK_CUSTOM_PAYLOAD: '{"text": [
                                          {
                                            "type": "rich_text",
                                            "elements": [
                                              {
                                                "type": "rich_text_section",
                                                "elements": [
                                                  {
                                                    "type": "text",
                                                    "text": "Name: ",
                                                    "style": {
                                                      "bold": true
                                                    }
                                                  },
                                                  {
                                                    "type": "text",
                                                    "text": "Zheng Jie Cheng\n"
                                                  },
                                                  {
                                                    "type": "text",
                                                    "text": "Metriculation: ",
                                                    "style": {
                                                      "bold": true
                                                    }
                                                  },
                                                  {
                                                    "type": "text",
                                                    "text": "e1327869\n"
                                                  },
                                                  {
                                                    "type": "text",
                                                    "text": "Email:",
                                                    "style": {
                                                      "bold": true
                                                    }
                                                  },
                                                  {
                                                    "type": "text",
                                                    "text": " "
                                                  },
                                                  {
                                                    "type": "link",
                                                    "url": "mailto:e1327869@u.nu",
                                                    "text": "e1327869@u.nu"
                                                  },
                                                  {
                                                    "type": "link",
                                                    "url": "http://s.edu",
                                                    "text": "s.edu"
                                                  },
                                                  {
                                                    "type": "text",
                                                    "text": "\n"
                                                  },
                                                  {
                                                    "type": "text",
                                                    "text": "Git:",
                                                    "style": {
                                                      "bold": true
                                                    }
                                                  },
                                                  {
                                                    "type": "text",
                                                    "text": " "
                                                  },
                                                  {
                                                    "type": "link",
                                                    "url": "https://github.com/HowdyBunny/CICDWorkshop"
                                                  },
                                                  {
                                                    "type": "text",
                                                    "text": "\n"
                                                  },
                                                  {
                                                    "type": "text",
                                                    "text": "Image: ",
                                                    "style": {
                                                      "bold": true
                                                    }
                                                  },
                                                  {
                                                    "type": "link",
                                                    "url": "https://github.com/HowdyBunny/CICDWorkshop"
                                                  }
                                                ]
                                              }
                                            ]
                                          }
                                        ]
                                      }'
                SLACK_WEBHOOK: ${{ secrets.CICDTEST_BYMYSELF }}
                
            
            
        