name: Build and Push
on:
    push:
        branches:
            - 'release/v[0-9]+.[0-9]+'
jobs:
    scan:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with: 
                ref: ${{ github.ref }} 

            - name: Run trivy scanner
              uses: aquasecurity/trivy-action@master
              with:
                format: 'table'
                scan-type: 'fs'
                severity: 'CRITICAL'
                exit-code: '1'
                ignore-unfixed: true
                output: 'trivy-results.txt'
            
           
            
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                push: true
                tags: HowdyBunny/go-fortune:${{ github.sha }}

            
            
            - name: Install Cosign
              uses: sigstore/cosign-installer@v3.5.0
            
            
            - name: Sign image with a key
              run: |
                images=""
                for tag in ${TAGS}; do
                  images+="${tag}"
                done
                cosign sign --yes --key env://COSIGN_PRIVATE_KEY ${images}
              env:
                TAGS: 'HowdyBunny/go-fortune:${{ github.sha }}'
                COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
                
                
            - name: Slack Notification
              uses: rtCamp/action-slack-notify@v2
              env:
                SLACK_CHANNEL: workshopsubtest
                SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
                SLACK_ICON: https://github.com/rtCamp.png?size=48
                
                SLACK_TITLE: Scan failed - Zheng Jie Cheng
                SLACK_MESSAGE: 'Failed trivy scan, see uploaded report'
                SLACK_TOKEN: ${{ secrets.CICDTEST_BYMYSELF_TOKEN }}
                
            - name: Post Files to slack
              uses: MeilCli/slack-upload-file@v4
              with:
                slack_token: ${{ secrets.CICDTEST_BYMYSELF_TOKEN }}
                channel_id: 'C071M1LB3DM'
                content: 'file content'
                file_type: 'text'
                file_name: 'trivy-results.txt'
                title: 'title of file'
                initial_comment: 'post by slack-upload-file'
            
        