name: Build and Push
on:
    push:
        branches:
            - 'release/v[0-9]+.[0-9]+'
jobs:
    CICD:
      runs-on: ubuntu-latest
      if: |
        !startsWith(github.event.head_commit.message, '#NORUN')
      steps:
          - uses: actions/checkout@v3
            with: 
              ref: ${{ github.ref }} 

          - name: Run trivy scanner
            uses: aquasecurity/trivy-action@master
            with:
              format: 'table'
              scan-type: 'fs'
              severity: 'CRITICAL'
              exit-code: '0'
              ignore-unfixed: true
              output: 'trivy-results.txt'
          
          
          
          - name: Set up QEMU
            uses: docker/setup-qemu-action@v3
          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3
          - name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}
          - name: Build and push
            uses: docker/build-push-action@v5
            with:
              push: true
              tags: howdybunny/go-fortune:${{ github.sha }}

          
          - name: Install Cosign
            uses: sigstore/cosign-installer@v3.5.0
          
          
          - name: Sign image with a key
            run: |
              images=""
              for tag in ${TAGS}; do
                images+="${tag}"
              done
              cosign sign --yes --key env://COSIGN_PRIVATE_KEY ${images}
              cosign verify --key cosign.pub ${images}
              
            env:
              COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
              COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
              TAGS: 'howdybunny/go-fortune:${{ github.sha }}'
              
              
              
          - name: Slack Notification
            uses: rtCamp/action-slack-notify@v2
            env:
              SLACK_CHANNEL: test-submission
              SLACK_COLOR: ${{ job.status }}
              SLACK_TITLE: Image build and signed
              ENABLE_ESCAPES: true
              SLACK_MESSAGE: '*Name:* Zheng Jie Cheng\n*Metriculation:* A0290838R\n*Email:* e1327869@u.nus.edu\n*Git:* https://github.com/${{ github.repository }}\n*Image:* https://hub.docker.com/repository/docker/howdybunny/go-fortune'
              SLACK_WEBHOOK: ${{ secrets.CICDWORKSHOP_URL }}
              
          
          
      