name: Build and Push
on:
    push:
        branches:
            - 'release/v[0-9]+.[0-9]+'
jobs:
    scan:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
              with: 
                ref: ${{ github.ref }} 
            - name: Run trivy scanner
              uses: aquasecurity/trivy-action@master
              with:
                scan-type: 'fs'
                severity: 'HIGH'
                exit-code: '0'
                format: 'table'
                output: 'trivy-results.txt'
            
            - name: Slack Notification
              uses: rtCamp/action-slack-notify@v2
              env:
                  SLACK_CHANNEL: workshopsubtest
                  SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
                  SLACK_ICON: https://github.com/rtCamp.png?size=48
                  
                  SLACK_TITLE: Scan failed - Zheng Jie Cheng
                  SLACK_MESSAGE: 'Failed trivy scan, see uploaded report'
                  SLACK_TOKEN: ${{ secrets.CICDTEST_BYMYSELF_TOKEN }}
            - name: Slack Files
              uses: rtCamp/action-slack-notify@v2
              env:
                SLACK_CHANNEL: workshopsubtest
                
                SLACK_FILE_UPLOAD: trivy-results.txt
                SLACK_TOKEN: ${{ secrets.CICDTEST_BYMYSELF_TOKEN }}
                


            
    