name: Build and Push
on:
    push:
        branches:
            - 'release/v[0-9]+.[0-9]+'
jobs:
    scan:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
              with: 
                ref: ${{ github.ref }} 
            - name: Run trivy scanner
              uses: aquasecurity/trivy-action@master
              with:
                format: 'table'
                scan-type: 'fs'
                severity: 'HIGH'
                exit-code: '0'
                ignore-unfixed: true
                output: 'trivy-results.txt'
              
            

            - name: Slack Notification
              uses: rtCamp/action-slack-notify@v2
              env:
                  SLACK_CHANNEL: workshopsubtest
                  SLACK_COLOR: failure
                  
                  SLACK_TITLE: Scan failed - Zheng Jie Cheng
                  SLACK_MESSAGE: 'Failed trivy scan, see uploaded report'
                  SLACK_WEBHOOK: ${{ secrets.CICDTEST_BYMYSELF }}

            - name: Post Files to slack
              uses: MeilCli/slack-upload-file@v4
              with:
                slack_token: ${{ secrets.CICDTEST_BYMYSELF_TOKEN }}
                channel_id: 'C071M1LB3DM'
                file_path: 'trivy-results.txt'
                file_type: 'text'
                initial_comment: 'Scan report by Zheng Jie Cheng'
            
            - name: Set Failure
              run: exit 1

            
                


            
    